### ISSUE TITLE
wrong url for .ui-icon-gripsmall-diagonal-se

### ISSUE THREAD

**Issue by maxim-s-barabash** [RobiNN1/elFinder-Material-Theme#1]
.ui-icon-gripsmall-diagonal-se {
  background: url("../../img/toolbar.png") 0 -496px no-repeat !important;
}

Whether it is necessary to fix?

.ui-icon-gripsmall-diagonal-se {
  background: url("images/toolbar.png") 0 -496px no-repeat !important;
}

**Comment by RobiNN1** [comment]
It's not a problem. This is icon for resize on down right corner. 

I'm working on a new version, all images will be replaced by icon fonts.

**Comment by maxim-s-barabash** [comment]
It is wonderful. Thank you.
