### ISSUE TITLE
File list header not always styled

### ISSUE THREAD

**Issue by tukusejssirs** [RobiNN1/elFinder-Material-Theme#10]
On phone, in list view of files, when there are no files, the list header is not styled (i.e. it is styled in the default theme of elFinder).

I tried to tweak your theme, but could not make it work.

See the screenshot below.

![Screenshot_20210402-101939](https://user-images.githubusercontent.com/5111894/113983007-bca69380-9849-11eb-83fe-e6b68142a251.jpg)

**Comment by RobiNN1** [comment]
Pracuje sa na oprave.

**Comment by tukusejssirs** [comment]
Vdaka.

**Comment by RobiNN1** [comment]
https://github.com/RobiNN1/elFinder-Material-Theme/commit/a8475014372f073d7844ccf34e235ee95964cf6f
