### ISSUE TITLE
How to use this theme ?

### ISSUE THREAD

**Issue by re-LIF3** [RobiNN1/elFinder-Material-Theme#12]
at preference menu, the no option theme ? how to add this ?
![Screenshot 2024-10-11 185813](https://github.com/user-attachments/assets/2676dde9-17bf-43a3-b7c7-c7dbc67e98fa)

**Comment by RobiNN1** [comment]
There is an installation guide https://github.com/RobiNN1/elFinder-Material-Theme?tab=readme-ov-file#installation you don't need to download anything, it uses files directly from github.

Here is official docs https://github.com/Studio-42/elFinder/wiki/How-to-load-CSS-with-RequireJS%3F
