### ISSUE TITLE
Odd visual effect in List View

### ISSUE THREAD

**Issue by donShakespeare** [RobiNN1/elFinder-Material-Theme#2]
Great theme, very official!

Here are some of my observations/feedback

Image showing files/folders in List View, with everyting selected (CTRL A)
Notice the alternate styles
Notice the table/column white selected heading
![image](https://cloud.githubusercontent.com/assets/5103329/25185313/e550db5a-24d1-11e7-9783-7c7f9d7dbb3f.png)

**Comment by RobiNN1** [comment]
Remove default elFinder theme ```css/theme.css```

**Comment by donShakespeare** [comment]
Without the official theme, many things become unusable. Did you succeed with this on version 2.1.23?

![image](https://cloud.githubusercontent.com/assets/5103329/25189683/b96d930e-24de-11e7-9d80-2d56f0f97bc8.png)

**Comment by RobiNN1** [comment]
I don't tested theme with latest version. Fix it over the weekend

**Comment by RobiNN1** [comment]
https://github.com/RobiNN1/elFinder-Material-Theme/commit/d3c37bc117f9c8cec288609755aba9b505fc30d7

**Comment by donShakespeare** [comment]
Probably the best themes for elFinder. Excellent design eye you have.

**Comment by RobiNN1** [comment]
Thanks
