### ISSUE TITLE
Unable to see the whole name of a file when renaming

### ISSUE THREAD

**Issue by jgagnon-planiso** [RobiNN1/elFinder-Material-Theme#5]
Hi,

When we want to rename a file in ListView, sometimes we cannot see the complete name of the file.

![image](https://user-images.githubusercontent.com/46540411/50929094-65c37100-142a-11e9-9f80-2927624fc99c.png)
![image](https://user-images.githubusercontent.com/46540411/50929119-7378f680-142a-11e9-82be-023fba140b89.png)
![image](https://user-images.githubusercontent.com/46540411/50929140-7ecc2200-142a-11e9-923f-a953387dbbbc.png)
![image](https://user-images.githubusercontent.com/46540411/50929146-82f83f80-142a-11e9-96a6-b643b5a10803.png)

Can this be fixed?
Thanks

**Comment by RobiNN1** [comment]
Fixed https://github.com/RobiNN1/elFinder-Material-Theme/commit/a33841ebf3fdc1e41ca292a6fe3f915213d2a854
