### ISSUE TITLE
Theme seems corrupted in the new 2.1.48 version

### ISSUE THREAD

**Issue by cristiangervasi** [RobiNN1/elFinder-Material-Theme#6]
Hi, i'm using the latest version of elFinder (2.1.48) and when i try to load the "theme.css" file in the <head> html tags, the file manager layout glitch completely.

I'm autoloading the elFinder main css files and the material theme css file because currently "cssAutoLoad" is not working.

I don't know if it's because of the update, i don't want you to hurry up, it's just to let you know.

Thanks for your work.

**Comment by RobiNN1** [comment]
Try this:
```javascript
bootCallback : function(fm, extraObj) {
    fm.bind('cssloaded', function() {
        fm.loadCss(["themes/Material/css/theme.min.css"]);
    });
}
```
it is alternative to
```javascript
cssAutoLoad: ["themes/Material/css/theme.min.css"]
```
