### ISSUE TITLE
File extension label too big

### ISSUE THREAD

**Issue by cristiangervasi** [RobiNN1/elFinder-Material-Theme#7]
Hi, i'm using the latest release of both elFinder (2.1.48) and the Material theme. 
When i set the CWD icon size to more than 0, the file extension labels are too big and overlapping each other. 
Here is an example with icon size 3:
![screenshot](https://user-images.githubusercontent.com/2169970/53895414-4e6fc100-4032-11e9-9a06-8870e6653bc4.png)

**Comment by RobiNN1** [comment]
Fixed
