### ISSUE TITLE
Colours are incorrect

### ISSUE THREAD

**Issue by jgagnon-planiso** [RobiNN1/elFinder-Material-Theme#8]
Hello,

It seems to have a problem for the colours in the css:

What I should have
![image](https://user-images.githubusercontent.com/46540411/56761770-2d8f3680-676c-11e9-9865-449794af8c30.png)

What I got:
![image](https://user-images.githubusercontent.com/46540411/56761864-6a5b2d80-676c-11e9-99df-f6e1ba59bccd.png)

Even if I'm using either of the three theme files.

**Comment by RobiNN1** [comment]
Latest version: 2.1.9

![screen](https://user-images.githubusercontent.com/11664877/56762673-ae682580-67a0-11e9-81b9-34d5a0cc11c0.png)

**Comment by jgagnon-planiso** [comment]
The cache has been removed -- the code is not even cached --, the plugins is loaded properly as indicated in linked you have provided, as we are using the same code in both development environments, but the problem is not fixed.

However, in the first image I have sent, the version 2.1.6 is used:
![image](https://user-images.githubusercontent.com/46540411/56809680-75609d00-6802-11e9-95ed-a7cd2b1c288e.png)

and in the second image, it is the version 2.1.9:
![image](https://user-images.githubusercontent.com/46540411/56809735-96c18900-6802-11e9-8bb1-b110392123fe.png)

**Comment by RobiNN1** [comment]
I cannot reproduce this issue. 

Maybe mixed styles with your page styles.

elFinder version? I only tested with the latest elfinder, theme should be compatible with the older elfinder, but I didn't test it.
Any additional screenshot?
The problem is manifested only in a light theme?

**Comment by jgagnon-planiso** [comment]
The version of elFinder is 2.1.49, the latest one.
![image](https://user-images.githubusercontent.com/46540411/56898609-74787700-6a5f-11e9-863b-5c5ff56dc65b.png)
The problem is manisfested only when i'm usign any of themes from "RobiNN1/elFinder-Material-Theme"

**Comment by RobiNN1** [comment]
Did you edit CSS?

That looks like mixed light/gray theme together or not properly loaded css.

```javascript
// Use options themes and theme. In setting you can toggle theme
themes : {
    // You can specify a manifest.
    default : 'https://cdn.jsdelivr.net/gh/RobiNN1/elFinder-Material-Theme/manifests/material-default.json',
    gray : 'https://cdn.jsdelivr.net/gh/RobiNN1/elFinder-Material-Theme/manifests/material-gray.json',
    light : 'https://cdn.jsdelivr.net/gh/RobiNN1/elFinder-Material-Theme/manifests/material-light.json',
},
theme : 'default',

// or load theme directly with cssAutoLoad option
cssAutoLoad: ["themes/Material/css/theme.min.css"],
```

**Comment by jgagnon-planiso** [comment]
Yes I did, I used cssAutoLoad option, but it doesn't work

**Comment by RobiNN1** [comment]
Got it. It's elFinder issue.
Default elfinder theme must be loaded first and then own theme.

![screen](https://user-images.githubusercontent.com/11664877/56904652-05227780-6a9f-11e9-91b3-115578af6a29.jpg)

**Comment by jgagnon-planiso** [comment]
Thanks
I will wait for elFinder update

**Comment by bateller** [comment]
I also had this issue today updating to elFinder v2.1.49

The fix appears to work (putting in a bind on 'cssloaded'). 

Thank you.
