### ISSUE TITLE
Toolbar text labels need styling

### ISSUE THREAD

**Issue by danielmpetrov** [RobiNN1/elFinder-Material-Theme#9]
Hi, good job on the theme!

Something I've just noticed is that the text labels in the toolbar (CSS class `elfinder-button-text`) are lacking alignment and spacing, refer to the screenshot below.

![toolbar-text-labels](https://user-images.githubusercontent.com/15656341/62775368-b9249d00-baa7-11e9-81bf-d5268e9153f9.PNG)

Those are enabled by right clicking on the elFinder toolbar, and selecting _Text label_.

My suggestion would be to add about 5px of margin between the icon and the label, and also align them in a way that the text is in the middle of the icon. But it's your theme, your decision!

Thank you,
Daniel

**Comment by RobiNN1** [comment]
Fixed https://github.com/RobiNN1/elFinder-Material-Theme/commit/5b76d754a4dbe912c2c46ae716091e9623df4901
